/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface GetSubjectById404Response
 */
export interface GetSubjectById404Response {
    /**
     *
     * @type {string}
     * @memberof GetSubjectById404Response
     */
    error?: string;
}

/**
 * Check if a given object implements the GetSubjectById404Response interface.
 */
export function instanceOfGetSubjectById404Response(value: object): value is GetSubjectById404Response {
    return true;
}

export function GetSubjectById404ResponseFromJSON(json: any): GetSubjectById404Response {
    return GetSubjectById404ResponseFromJSONTyped(json, false);
}

export function GetSubjectById404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSubjectById404Response {
    if (json == null) {
        return json;
    }
    return {

        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetSubjectById404ResponseToJSON(json: any): GetSubjectById404Response {
    return GetSubjectById404ResponseToJSONTyped(json, false);
}

export function GetSubjectById404ResponseToJSONTyped(value?: GetSubjectById404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'error': value['error'],
    };
}
