/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * JSON schema representing a syllabus structure
 * @export
 * @interface GetSchema200Response
 */
export interface GetSchema200Response {
    [key: string]: any | any;
    /**
     * Version identifier of the schema
     * @type {string}
     * @memberof GetSchema200Response
     */
    schemaVersion?: string;
}

/**
 * Check if a given object implements the GetSchema200Response interface.
 */
export function instanceOfGetSchema200Response(value: object): value is GetSchema200Response {
    return true;
}

export function GetSchema200ResponseFromJSON(json: any): GetSchema200Response {
    return GetSchema200ResponseFromJSONTyped(json, false);
}

export function GetSchema200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSchema200Response {
    if (json == null) {
        return json;
    }
    return {

            ...json,
        'schemaVersion': json['schemaVersion'] == null ? undefined : json['schemaVersion'],
    };
}

export function GetSchema200ResponseToJSON(json: any): GetSchema200Response {
    return GetSchema200ResponseToJSONTyped(json, false);
}

export function GetSchema200ResponseToJSONTyped(value?: GetSchema200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

            ...value,
        'schemaVersion': value['schemaVersion'],
    };
}
