/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A map of tag names to their usage counts
 * @export
 * @interface GetTags200Response
 */
export interface GetTags200Response {
    [key: string]: number | any;
    /**
     * Example tag count
     * @type {number}
     * @memberof GetTags200Response
     */
    exampleTag?: number;
}

/**
 * Check if a given object implements the GetTags200Response interface.
 */
export function instanceOfGetTags200Response(value: object): value is GetTags200Response {
    return true;
}

export function GetTags200ResponseFromJSON(json: any): GetTags200Response {
    return GetTags200ResponseFromJSONTyped(json, false);
}

export function GetTags200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTags200Response {
    if (json == null) {
        return json;
    }
    return {

            ...json,
        'exampleTag': json['exampleTag'] == null ? undefined : json['exampleTag'],
    };
}

export function GetTags200ResponseToJSON(json: any): GetTags200Response {
    return GetTags200ResponseToJSONTyped(json, false);
}

export function GetTags200ResponseToJSONTyped(value?: GetTags200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

            ...value,
        'exampleTag': value['exampleTag'],
    };
}
