/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SearchSyllabus200ResponsePagination
 */
export interface SearchSyllabus200ResponsePagination {
    /**
     *
     * @type {number}
     * @memberof SearchSyllabus200ResponsePagination
     */
    page?: number;
    /**
     *
     * @type {number}
     * @memberof SearchSyllabus200ResponsePagination
     */
    limit?: number;
    /**
     *
     * @type {number}
     * @memberof SearchSyllabus200ResponsePagination
     */
    total?: number;
    /**
     *
     * @type {number}
     * @memberof SearchSyllabus200ResponsePagination
     */
    pages?: number;
}

/**
 * Check if a given object implements the SearchSyllabus200ResponsePagination interface.
 */
export function instanceOfSearchSyllabus200ResponsePagination(value: object): value is SearchSyllabus200ResponsePagination {
    return true;
}

export function SearchSyllabus200ResponsePaginationFromJSON(json: any): SearchSyllabus200ResponsePagination {
    return SearchSyllabus200ResponsePaginationFromJSONTyped(json, false);
}

export function SearchSyllabus200ResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSyllabus200ResponsePagination {
    if (json == null) {
        return json;
    }
    return {

        'page': json['page'] == null ? undefined : json['page'],
        'limit': json['limit'] == null ? undefined : json['limit'],
        'total': json['total'] == null ? undefined : json['total'],
        'pages': json['pages'] == null ? undefined : json['pages'],
    };
}

export function SearchSyllabus200ResponsePaginationToJSON(json: any): SearchSyllabus200ResponsePagination {
    return SearchSyllabus200ResponsePaginationToJSONTyped(json, false);
}

export function SearchSyllabus200ResponsePaginationToJSONTyped(value?: SearchSyllabus200ResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'page': value['page'],
        'limit': value['limit'],
        'total': value['total'],
        'pages': value['pages'],
    };
}
