/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SearchSyllabus200ResponsePagination } from './SearchSyllabus200ResponsePagination';
import {
    SearchSyllabus200ResponsePaginationFromJSON,
    SearchSyllabus200ResponsePaginationFromJSONTyped,
    SearchSyllabus200ResponsePaginationToJSON,
    SearchSyllabus200ResponsePaginationToJSONTyped,
} from './SearchSyllabus200ResponsePagination';
import type { Syllabus } from './Syllabus';
import {
    SyllabusFromJSON,
    SyllabusFromJSONTyped,
    SyllabusToJSON,
    SyllabusToJSONTyped,
} from './Syllabus';

/**
 *
 * @export
 * @interface SearchSyllabus200Response
 */
export interface SearchSyllabus200Response {
    /**
     *
     * @type {Array<Syllabus>}
     * @memberof SearchSyllabus200Response
     */
    results?: Array<Syllabus>;
    /**
     *
     * @type {SearchSyllabus200ResponsePagination}
     * @memberof SearchSyllabus200Response
     */
    pagination?: SearchSyllabus200ResponsePagination;
}

/**
 * Check if a given object implements the SearchSyllabus200Response interface.
 */
export function instanceOfSearchSyllabus200Response(value: object): value is SearchSyllabus200Response {
    return true;
}

export function SearchSyllabus200ResponseFromJSON(json: any): SearchSyllabus200Response {
    return SearchSyllabus200ResponseFromJSONTyped(json, false);
}

export function SearchSyllabus200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSyllabus200Response {
    if (json == null) {
        return json;
    }
    return {

        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(SyllabusFromJSON)),
        'pagination': json['pagination'] == null ? undefined : SearchSyllabus200ResponsePaginationFromJSON(json['pagination']),
    };
}

export function SearchSyllabus200ResponseToJSON(json: any): SearchSyllabus200Response {
    return SearchSyllabus200ResponseToJSONTyped(json, false);
}

export function SearchSyllabus200ResponseToJSONTyped(value?: SearchSyllabus200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(SyllabusToJSON)),
        'pagination': SearchSyllabus200ResponsePaginationToJSON(value['pagination']),
    };
}
