/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubjectMeta
 */
export interface SubjectMeta {
    /**
     *
     * @type {string}
     * @memberof SubjectMeta
     */
    version?: string;
}

/**
 * Check if a given object implements the SubjectMeta interface.
 */
export function instanceOfSubjectMeta(value: object): value is SubjectMeta {
    return true;
}

export function SubjectMetaFromJSON(json: any): SubjectMeta {
    return SubjectMetaFromJSONTyped(json, false);
}

export function SubjectMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectMeta {
    if (json == null) {
        return json;
    }
    return {

        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function SubjectMetaToJSON(json: any): SubjectMeta {
    return SubjectMetaToJSONTyped(json, false);
}

export function SubjectMetaToJSONTyped(value?: SubjectMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'version': value['version'],
    };
}
