/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubjectMeta } from './SubjectMeta';
import {
    SubjectMetaFromJSON,
    SubjectMetaFromJSONTyped,
    SubjectMetaToJSON,
    SubjectMetaToJSONTyped,
} from './SubjectMeta';
import type { SubjectUnitsInner } from './SubjectUnitsInner';
import {
    SubjectUnitsInnerFromJSON,
    SubjectUnitsInnerFromJSONTyped,
    SubjectUnitsInnerToJSON,
    SubjectUnitsInnerToJSONTyped,
} from './SubjectUnitsInner';

/**
 *
 * @export
 * @interface Subject
 */
export interface Subject {
    /**
     *
     * @type {string}
     * @memberof Subject
     */
    code?: string;
    /**
     *
     * @type {string}
     * @memberof Subject
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof Subject
     */
    description?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof Subject
     */
    objectives?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof Subject
     */
    prerequisites?: Array<string>;
    /**
     *
     * @type {Array<SubjectUnitsInner>}
     * @memberof Subject
     */
    units?: Array<SubjectUnitsInner>;
    /**
     *
     * @type {Array<string>}
     * @memberof Subject
     */
    tags?: Array<string>;
    /**
     *
     * @type {Array<string>}
     * @memberof Subject
     */
    suggestedBooks?: Array<string>;
    /**
     *
     * @type {SubjectMeta}
     * @memberof Subject
     */
    meta?: SubjectMeta;
}

/**
 * Check if a given object implements the Subject interface.
 */
export function instanceOfSubject(value: object): value is Subject {
    return true;
}

export function SubjectFromJSON(json: any): Subject {
    return SubjectFromJSONTyped(json, false);
}

export function SubjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Subject {
    if (json == null) {
        return json;
    }
    return {

        'code': json['code'] == null ? undefined : json['code'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'objectives': json['objectives'] == null ? undefined : json['objectives'],
        'prerequisites': json['prerequisites'] == null ? undefined : json['prerequisites'],
        'units': json['units'] == null ? undefined : ((json['units'] as Array<any>).map(SubjectUnitsInnerFromJSON)),
        'tags': json['tags'] == null ? undefined : json['tags'],
        'suggestedBooks': json['suggested_books'] == null ? undefined : json['suggested_books'],
        'meta': json['meta'] == null ? undefined : SubjectMetaFromJSON(json['meta']),
    };
}

export function SubjectToJSON(json: any): Subject {
    return SubjectToJSONTyped(json, false);
}

export function SubjectToJSONTyped(value?: Subject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'code': value['code'],
        'name': value['name'],
        'description': value['description'],
        'objectives': value['objectives'],
        'prerequisites': value['prerequisites'],
        'units': value['units'] == null ? undefined : ((value['units'] as Array<any>).map(SubjectUnitsInnerToJSON)),
        'tags': value['tags'],
        'suggested_books': value['suggestedBooks'],
        'meta': SubjectMetaToJSON(value['meta']),
    };
}
