/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SubjectUnitsInner
 */
export interface SubjectUnitsInner {
    /**
     *
     * @type {number}
     * @memberof SubjectUnitsInner
     */
    unit?: number;
    /**
     *
     * @type {string}
     * @memberof SubjectUnitsInner
     */
    title?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof SubjectUnitsInner
     */
    topics?: Array<string>;
}

/**
 * Check if a given object implements the SubjectUnitsInner interface.
 */
export function instanceOfSubjectUnitsInner(value: object): value is SubjectUnitsInner {
    return true;
}

export function SubjectUnitsInnerFromJSON(json: any): SubjectUnitsInner {
    return SubjectUnitsInnerFromJSONTyped(json, false);
}

export function SubjectUnitsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectUnitsInner {
    if (json == null) {
        return json;
    }
    return {

        'unit': json['unit'] == null ? undefined : json['unit'],
        'title': json['title'] == null ? undefined : json['title'],
        'topics': json['topics'] == null ? undefined : json['topics'],
    };
}

export function SubjectUnitsInnerToJSON(json: any): SubjectUnitsInner {
    return SubjectUnitsInnerToJSONTyped(json, false);
}

export function SubjectUnitsInnerToJSONTyped(value?: SubjectUnitsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'unit': value['unit'],
        'title': value['title'],
        'topics': value['topics'],
    };
}
