/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Subject } from './Subject';
import {
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
    SubjectToJSONTyped,
} from './Subject';

/**
 *
 * @export
 * @interface Syllabus
 */
export interface Syllabus {
    /**
     *
     * @type {string}
     * @memberof Syllabus
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof Syllabus
     */
    branch?: string;
    /**
     *
     * @type {number}
     * @memberof Syllabus
     */
    semester?: number;
    /**
     *
     * @type {Subject}
     * @memberof Syllabus
     */
    subject?: Subject;
}

/**
 * Check if a given object implements the Syllabus interface.
 */
export function instanceOfSyllabus(value: object): value is Syllabus {
    return true;
}

export function SyllabusFromJSON(json: any): Syllabus {
    return SyllabusFromJSONTyped(json, false);
}

export function SyllabusFromJSONTyped(json: any, ignoreDiscriminator: boolean): Syllabus {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'semester': json['semester'] == null ? undefined : json['semester'],
        'subject': json['subject'] == null ? undefined : SubjectFromJSON(json['subject']),
    };
}

export function SyllabusToJSON(json: any): Syllabus {
    return SyllabusToJSONTyped(json, false);
}

export function SyllabusToJSONTyped(value?: Syllabus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'id': value['id'],
        'branch': value['branch'],
        'semester': value['semester'],
        'subject': SubjectToJSON(value['subject']),
    };
}
