/* tslint:disable */
/* eslint-disable */
/**
 * Syllabus API
 * API for managing and searching syllabi
 *
 * The version of the OpenAPI document: v1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetSchema200Response,
  GetSubjectById404Response,
  GetTags200Response,
  SearchSyllabus200Response,
  Syllabus,
} from '../models/index';
import {
    GetSchema200ResponseFromJSON,
    GetSchema200ResponseToJSON,
    GetSubjectById404ResponseFromJSON,
    GetSubjectById404ResponseToJSON,
    GetTags200ResponseFromJSON,
    GetTags200ResponseToJSON,
    SearchSyllabus200ResponseFromJSON,
    SearchSyllabus200ResponseToJSON,
    SyllabusFromJSON,
    SyllabusToJSON,
} from '../models/index';

export interface GetSubjectByIdRequest {
    id: string;
}

export interface GetSubjectsByBranchAndSemesterRequest {
    branch: string;
    semester: number;
}

export interface SearchSyllabusRequest {
    q?: string;
    branch?: string;
    semester?: number;
    tags?: string;
    skill?: string;
    page?: number;
    limit?: number;
}

/**
 *
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get contributing guidelines as plain text
     */
    async getContributingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/contributing`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Get contributing guidelines as plain text
     */
    async getContributing(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.getContributingRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get the syllabus schema
     */
    async getSchemaRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetSchema200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/syllabus/schema`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetSchema200ResponseFromJSON(jsonValue));
    }

    /**
     * Get the syllabus schema
     */
    async getSchema(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetSchema200Response> {
        const response = await this.getSchemaRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get a single subject by ID
     */
    async getSubjectByIdRaw(requestParameters: GetSubjectByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Syllabus>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSubjectById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/syllabus/subject/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SyllabusFromJSON(jsonValue));
    }

    /**
     * Get a single subject by ID
     */
    async getSubjectById(requestParameters: GetSubjectByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Syllabus> {
        const response = await this.getSubjectByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get subjects for a specific branch and semester
     */
    async getSubjectsByBranchAndSemesterRaw(requestParameters: GetSubjectsByBranchAndSemesterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Syllabus>>> {
        if (requestParameters['branch'] == null) {
            throw new runtime.RequiredError(
                'branch',
                'Required parameter "branch" was null or undefined when calling getSubjectsByBranchAndSemester().'
            );
        }

        if (requestParameters['semester'] == null) {
            throw new runtime.RequiredError(
                'semester',
                'Required parameter "semester" was null or undefined when calling getSubjectsByBranchAndSemester().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/syllabus/{branch}/{semester}`;
        urlPath = urlPath.replace(`{${"branch"}}`, encodeURIComponent(String(requestParameters['branch'])));
        urlPath = urlPath.replace(`{${"semester"}}`, encodeURIComponent(String(requestParameters['semester'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SyllabusFromJSON));
    }

    /**
     * Get subjects for a specific branch and semester
     */
    async getSubjectsByBranchAndSemester(requestParameters: GetSubjectsByBranchAndSemesterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Syllabus>> {
        const response = await this.getSubjectsByBranchAndSemesterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get branches, semesters, and subject counts
     */
    async getSyllabusRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: { [key: string]: number; }; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/syllabus`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Get branches, semesters, and subject counts
     */
    async getSyllabus(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: { [key: string]: number; }; }> {
        const response = await this.getSyllabusRaw(initOverrides);
        return await response.value();
    }

    /**
     * Get all tags with counts
     */
    async getTagsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTags200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/syllabus/tags`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTags200ResponseFromJSON(jsonValue));
    }

    /**
     * Get all tags with counts
     */
    async getTags(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTags200Response> {
        const response = await this.getTagsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Search syllabi
     */
    async searchSyllabusRaw(requestParameters: SearchSyllabusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SearchSyllabus200Response>> {
        const queryParameters: any = {};

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['branch'] != null) {
            queryParameters['branch'] = requestParameters['branch'];
        }

        if (requestParameters['semester'] != null) {
            queryParameters['semester'] = requestParameters['semester'];
        }

        if (requestParameters['tags'] != null) {
            queryParameters['tags'] = requestParameters['tags'];
        }

        if (requestParameters['skill'] != null) {
            queryParameters['skill'] = requestParameters['skill'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/syllabus/search`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SearchSyllabus200ResponseFromJSON(jsonValue));
    }

    /**
     * Search syllabi
     */
    async searchSyllabus(requestParameters: SearchSyllabusRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SearchSyllabus200Response> {
        const response = await this.searchSyllabusRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
